### ISSUE TITLE
version

### ISSUE THREAD

**Issue by mens-artis** [automl/SMAC3#1080]
It seems to me that there are problems with debugging with this version of SMAC. When it crashes, it is unclear why. The inline documentation is like an ant hill. If you want to do HPO on some problem, then SMAC should work out of the box.

```[DEBUG][smbo.py:312] Remaining wallclock time: 29092.62648487091; Remaining cpu time: inf; Remaining trials: 42
[DEBUG][smbo.py:147] Calling ask...
[DEBUG][successive_halving.py:396] --- Yielding 1/1 for config e38e4d in stage 0 with seed 0...
[DEBUG][smbo.py:162] ...and received a new trial.
[DEBUG][dask_runner.py:139] No worker available. Waiting for one to be available...

0.20029999315738678

[DEBUG][runhistory.py:1046] Update cost for config 6616a6.
[DEBUG][smbo.py:216] Tell method was called with cost 0.7997000217437744 (SUCCESS).
[DEBUG][abstract_intensifier.py:494] No relevant instances evaluated for config 6616a6. Updating incumbents is skipped.
[DEBUG][smbo.py:312] Remaining wallclock time: 27619.465901374817; Remaining cpu time: inf; Remaining trials: 41
[DEBUG][smbo.py:147] Calling ask...
[DEBUG][successive_halving.py:410] --- Could not compare configs because not all trials have been evaluated yet.
[DEBUG][successive_halving.py:384] Updating tracker:
[DEBUG][successive_halving.py:396] --- Yielding 0/1 for config e9988a in stage 0 with seed 0...
[DEBUG][successive_halving.py:396] --- Yielding 0/1 for config b8a171 in stage 0 with seed 0...
[DEBUG][successive_halving.py:396] --- Yielding 0/1 for config 5562b3 in stage 0 with seed 0...
[DEBUG][successive_halving.py:396] --- Yielding 0/1 for config 55d239 in stage 0 with seed 0...
[DEBUG][successive_halving.py:396] --- Yielding 0/1 for config 5600f3 in stage 0 with seed 0...
[DEBUG][successive_halving.py:396] --- Yielding 0/1 for config 6616a6 in stage 0 with seed 0...
[DEBUG][successive_halving.py:396] --- Yielding 0/1 for config a35e95 in stage 0 with seed 0...
[DEBUG][successive_halving.py:396] --- Yielding 0/1 for config c4d751 in stage 0 with seed 0...
[DEBUG][successive_halving.py:396] --- Yielding 0/1 for config e38e4d in stage 0 with seed 0...
[DEBUG][successive_halving.py:410] --- Could not compare configs because not all trials have been evaluated yet.
[DEBUG][abstract_encoder.py:262] Transforming RunHistory into X, y format...
[DEBUG][abstract_encoder.py:282] Converted 6 observations.

ConfigSpace/util.py:199: hp_name:steps_per_epoch, hp:steps_per_epoch, Type: UniformInteger, Range: [100, 200], Default: 100, Q: 50, value:0.9950496029801195, random:RandomState(MT19937), stdev:0.05

Traceback (most recent call last):
  File "/home/u/venv/lib/python3.10/site-packages/ConfigSpace/util.py", line 200, in get_one_exchange_neighbourhood
    neighbors = hp.get_neighbors(
  File "ConfigSpace/hyperparameters/uniform_integer.pyx", line 291, in ConfigSpace.hyperparameters.uniform_integer.UniformIntegerHyperparameter.get_neighbors
StopIteration

The above exception was the direct cause of the following exception:```

**Comment by alexandertornede** [comment]
Thank you for reporting thins. Do you have any code to reproduce this?
