### ISSUE TITLE
AttributeError in TargetFunctionRunner

### ISSUE THREAD

**Issue by RSD6170** [automl/SMAC3#1176]
#### Description

When using SMAC to optimize the runtime of an algorithm, the error report in `runhistory.json` does not report the raised exception, but an SMAC-internal error in `TargetFunctionRunner`, namely that the `crash_cost` attribute does not exist as
https://github.com/automl/SMAC3/blob/9d194754a5fed3ec48be06987cfc24ee99b76af5/smac/runner/target_function_runner.py#L238
misses an underscore in comparison to
https://github.com/automl/SMAC3/blob/9d194754a5fed3ec48be06987cfc24ee99b76af5/smac/runner/abstract_runner.py#L64
#### Actual Results

Taken from `runhistory.json`:
```
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/learning_History/lib/python3.10/site-packages/smac/runner/abstract_runner.py", line 110, in run_wrapper
    status, cost, runtime, additional_info = self.run(
  File "/home/ubuntu/miniconda3/envs/learning_History/lib/python3.10/site-packages/smac/runner/target_function_runner.py", line 238, in run
    cost = self.crash_cost
AttributeError: 'TargetFunctionRunner' object has no attribute 'crash_cost'
```
#### Versions

 2.2.0

**Comment by benjamc** [comment]
Hi RSD6170,
thanks for letting us know.
The issue will be fixed via this PR #1177 and will be soon in the next release.
Best

**Comment by benjamc** [comment]
Closed by #1177
