### ISSUE TITLE
overall_obj = mean

### ISSUE THREAD

**Issue by mlindauer** [automl/SMAC3#165]
Scenario File with:
```
overall_obj = mean
```

leads to the following error message:

```
Traceback (most recent call last):
  File "/home/lindauer/git/SMAC3/scripts/smac", line 20, in <module>
    smac.main_cli()
  File "/home/lindauer/git/SMAC3/smac/smac_cli.py", line 48, in main_cli
    scen = Scenario(args_.scenario_file, misc_args)
  File "/home/lindauer/git/SMAC3/smac/scenario/scenario.py", line 94, in __init__
    self._transform_arguments()
  File "/home/lindauer/git/SMAC3/smac/scenario/scenario.py", line 265, in _transform_arguments
    self.par_factor = int(self.overall_obj[4:])
ValueError: invalid literal for int() with base 10: ''
```

**Comment by shukon** [comment]
Currently, `mean` as well as `par` require a par-factor, such as `mean10`. I am not sure if this is intended, since it is tested for in `test_scenario`, lines 53, 82 and 101.
Would a fix be to automatically use 1 as par-factor when objective is mean or rather set a default par-factor for mean (or in general) that is used when there is none provided? What is the difference (in terms of source code) between mean and par?

**Comment by mlindauer** [comment]
yes, a default of par-factor=1 would be good.
PAR1 = Mean
We only allow "mean10" (and co) because of backwards compatibility to ParamILS.
