### ISSUE TITLE
LeadingOnes Example broken

### ISSUE THREAD

**Issue by mlindauer** [automl/SMAC3#215]
```
$ python leadingones.py 
INFO:smac.scenario.scenario.Scenario:Output to smac3-output_2017-04-05_10:24:04
DEBUG:smac.scenario.scenario.Scenario:Output directory does not exist! Will be created.
DEBUG:smac.scenario.scenario.Scenario:Writing scenario-file to smac3-output_2017-04-05_10:24:04/scenario.txt.
Traceback (most recent call last):
  File "leadingones.py", line 57, in <module>
    "deterministic": "true"
  File "/home/lindauer/anaconda3/lib/python3.5/site-packages/smac-0.4.0-py3.5.egg/smac/scenario/scenario.py", line 105, in __init__
  File "/home/lindauer/anaconda3/lib/python3.5/site-packages/smac-0.4.0-py3.5.egg/smac/utils/io/output_writer.py", line 61, in write_scenario_file
  File "/home/lindauer/anaconda3/lib/python3.5/site-packages/smac-0.4.0-py3.5.egg/smac/utils/io/output_writer.py", line 100, in _parse_argument
  File "/home/lindauer/anaconda3/lib/python3.5/site-packages/smac-0.4.0-py3.5.egg/smac/utils/io/output_writer.py", line 169, in write_pcs_file
  File "/home/lindauer/anaconda3/lib/python3.5/site-packages/ConfigSpace-0.3.2-py3.5.egg/ConfigSpace/io/pcs.py", line 330, in write
    condition_lines.write(build_condition(condition))
  File "/home/lindauer/anaconda3/lib/python3.5/site-packages/ConfigSpace-0.3.2-py3.5.egg/ConfigSpace/io/pcs.py", line 125, in build_condition
    ", ".join(condition.values))
TypeError: sequence item 0: expected str instance, int found
```
@mfeurer Is it intended that conditionals on categoricals only accept str and not ints anymore?

**Comment by mlindauer** [comment]
will be removed in the Docu PR

**Comment by mfeurer** [comment]
Documentation PR is merged. Can this be closed?

**Comment by mlindauer** [comment]
yes.
