### ISSUE TITLE
smac.configspace.pcs.read does not consider OrdinalHyperparameters

### ISSUE THREAD

**Issue by mr42** [automl/SMAC3#258]
I got the following error, when I use the OrdinalHyperparameter `x2 ordinal {0,15} [0]' in the parameter.pcs of the branin example.

`python ../../scripts/smac --scenario branin_scenario.txt
INFO:smac.smac_cli.SMACCLI:SMAC call: ../../scripts/smac --scenario branin_scenario.txt
INFO:smac.scenario.scenario.Scenario:Reading scenario file: branin_scenario.txt
Traceback (most recent call last):
  File "/home/mrudolph/SMAC3/smac/scenario/scenario.py", line 352, in _transform_arguments
    self.cs = pcs.read(pcs_str)
  File "/home/mrudolph/anaconda3/lib/python3.6/site-packages/ConfigSpace/io/pcs.py", line 232, in read
    raise NotImplementedError("Could not parse: %s" % line)
NotImplementedError: Could not parse: x2 ordinal {0,15} [0]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../scripts/smac", line 20, in <module>
    smac.main_cli()
  File "/home/mrudolph/SMAC3/smac/smac_cli.py", line 51, in main_cli
    run_id=args_.seed)
  File "/home/mrudolph/SMAC3/smac/scenario/scenario.py", line 102, in __init__
    self._transform_arguments()
  File "/home/mrudolph/SMAC3/smac/scenario/scenario.py", line 355, in _transform_arguments
    self.cs = pcs_new.read(pcs_str)
  File "/home/mrudolph/anaconda3/lib/python3.6/site-packages/ConfigSpace/io/pcs_new.py", line 309, in read
    raise NotImplementedError("Could not parse: %s" % line)
NotImplementedError: Could not parse: x1 [-5,10] [0]
`

**Comment by KEggensperger** [comment]
From the error messages I assume that your pcs file looks looks like this:

`x2 ordinal {0,15} [0]`
`x1 [-5,10] [0]`

which is a mix of the old and new format and causes the error. Adding `real` to the second line should fix your problem.

First, the scenario tries the old format (and crashes `NotImplementedError: Could not parse: x2 ordinal {0,15} [0]`) and then tries the new format (and crashes again `NotImplementedError: Could not parse: x1 [-5,10] [0]`)

**Comment by mr42** [comment]
I tried your suggestion. My pcs looks like the following now:
`x1 real [-5,10] [0]`
`x2 ordinal {0,15} [0]`

Running the branin example again, causes the following error.

python ../../scripts/smac --scenario branin_scenario.txt
INFO:smac.smac_cli.SMACCLI:SMAC call: ../../scripts/smac --scenario branin_scenario.txt
INFO:smac.scenario.scenario.Scenario:Reading scenario file: branin_scenario.txt
INFO:smac.scenario.scenario.Scenario:Output to smac3-output_2017-05-30_17:01:23_(152364)
INFO:smac.stats.stats.Stats:##########################################################
INFO:smac.stats.stats.Stats:Statistics:
INFO:smac.stats.stats.Stats:#Incumbent changed: 0
INFO:smac.stats.stats.Stats:#Target algorithm runs: 1 / 500.0
INFO:smac.stats.stats.Stats:Used wallclock time: 0.10 / inf sec
INFO:smac.stats.stats.Stats:Used target algorithm runtime: -1.00 / inf sec
INFO:smac.stats.stats.Stats:##########################################################
INFO:smac.facade.smac_facade.SMAC:Final Incumbent: Configuration:
  x1, Value: 0.0
  x2, Value: '0'

Traceback (most recent call last):
  File "../../scripts/smac", line 20, in <module>
    smac.main_cli()
  File "/home/mrudolph/SMAC3/smac/smac_cli.py", line 86, in main_cli
    optimizer.optimize()
  File "/home/mrudolph/SMAC3/smac/facade/smac_facade.py", line 339, in optimize
    incumbent = self.solver.run()
  File "/home/mrudolph/SMAC3/smac/optimizer/smbo.py", line 123, in run
    challengers = self.choose_next(X, Y)
  File "/home/mrudolph/SMAC3/smac/optimizer/smbo.py", line 184, in choose_next
    self.model.train(X, Y)
  File "/home/mrudolph/SMAC3/smac/epm/base_epm.py", line 94, in train
    return self._train(X, Y)
  File "/home/mrudolph/SMAC3/smac/epm/rf_with_instances.py", line 123, in _train
    data = self.__init_data_container(self.X, self.y)
  File "/home/mrudolph/SMAC3/smac/epm/rf_with_instances.py", line 147, in __init_data_container
    data.set_type_of_feature(i, mn)
  File "/home/mrudolph/anaconda3/lib/python3.6/site-packages/pyrfr/regression.py", line 777, in set_type_of_feature
    return _regression.default_data_container_set_type_of_feature(self, index, type)
TypeError: in method 'default_data_container_set_type_of_feature', argument 3 of type 'unsigned int'

**Comment by mr42** [comment]
I tried to debug a bit. Here are my results:

1. self.bounds in rf_with_instances.py is [[0.0 1.0] [nan nan]] -> The first nan value in [nan nan] causes the TypeError

2. The RandomForestWithInstances is initialized in line 126 in the constructor of the class SMAC which is located in smac_facade.py
3. In the same constructor the bounds for the RandomForestWithInstances are set by the line 124 
`types, bounds = get_types(scenario.cs, scenario.feature_array)`
4. The called get_types method which is located in util_funcs.py considers all types of hyperparameters except the OrdinalHyperparemter.
5. That's the reason why the bounds are [nan nan].

Can you please add the case OrdinalHyperparameter there?

**Comment by mr42** [comment]
The program starts now, but hungs up at the first Search for next configuration.
My pcs file looks the following:
`x1 real [-5, 10] [0]`
`x2 ordinal {0,15} [0]`
Here is the console output:

python ../../scripts/smac --scenario branin_scenario.txt --verbose DEBUG
INFO:smac.smac_cli.SMACCLI:SMAC call: ../../scripts/smac --scenario branin_scenario.txt --verbose DEBUG
2017-05-31 17:14:10:INFO:smac.scenario.scenario.Scenario:Reading scenario file: branin_scenario.txt
2017-05-31 17:14:10:DEBUG:smac.scenario.scenario.Scenario:Could not parse pcs file with old format; trying new format next
2017-05-31 17:14:10:INFO:smac.scenario.scenario.Scenario:Output to smac3-output_2017-05-31_17:14:10_(489148)
2017-05-31 17:14:10:DEBUG:smac.scenario.scenario.Scenario:Output directory does not exist! Will be created.
2017-05-31 17:14:10:DEBUG:smac.scenario.scenario.Scenario:Writing scenario-file to smac3-output_2017-05-31_17:14:10_(489148)_run1/scenario.txt.
2017-05-31 17:14:10:DEBUG:smac.scenario.scenario.Scenario:Scenario Options:
2017-05-31 17:14:10:DEBUG:smac.scenario.scenario.Scenario:intensification_percentage = 0.5
2017-05-31 17:14:10:DEBUG:smac.scenario.scenario.Scenario:minR = 1
2017-05-31 17:14:10:DEBUG:smac.scenario.scenario.Scenario:algo_runs_timelimit = inf
2017-05-31 17:14:10:DEBUG:smac.scenario.scenario.Scenario:ta_run_limit = 500.0
2017-05-31 17:14:10:DEBUG:smac.scenario.scenario.Scenario:always_race_default = False
2017-05-31 17:14:10:DEBUG:smac.scenario.scenario.Scenario:pcs_fn = branin_pcs.pcs
2017-05-31 17:14:10:DEBUG:smac.scenario.scenario.Scenario:run_obj = quality
2017-05-31 17:14:10:DEBUG:smac.scenario.scenario.Scenario:wallclock_limit = inf
2017-05-31 17:14:10:DEBUG:smac.scenario.scenario.Scenario:cost_for_crash = 2147483647.0
2017-05-31 17:14:10:DEBUG:smac.scenario.scenario.Scenario:abort_on_first_run_crash = True
2017-05-31 17:14:10:DEBUG:smac.scenario.scenario.Scenario:deterministic = True
2017-05-31 17:14:10:DEBUG:smac.scenario.scenario.Scenario:output_dir = smac3-output_2017-05-31_17:14:10_(489148)
2017-05-31 17:14:10:DEBUG:smac.scenario.scenario.Scenario:initial_incumbent = DEFAULT
2017-05-31 17:14:10:DEBUG:smac.scenario.scenario.Scenario:maxR = 2000
2017-05-31 17:14:10:DEBUG:smac.scenario.scenario.Scenario:shared_model = False
2017-05-31 17:14:10:DEBUG:smac.scenario.scenario.Scenario:overall_obj = par10
2017-05-31 17:14:10:DEBUG:smac.scenario.scenario.Scenario:execdir = .
2017-05-31 17:14:10:DEBUG:smac.tae.execute_ta_run_old.ExecuteTARunOld:Calling: python branin.py 0 0 99999999999999.0 0 0 -x1 0.0 -x2 0
2017-05-31 17:14:10:DEBUG:smac.tae.execute_ta_run_old.ExecuteTARunOld:Stdout: Result for SMAC: SUCCESS, -1, -1, 55.602113, 0

2017-05-31 17:14:10:DEBUG:smac.tae.execute_ta_run_old.ExecuteTARunOld:Stderr: 
2017-05-31 17:14:10:DEBUG:smac.tae.execute_ta_run_old.ExecuteTARunOld:Return: Status: <StatusType.SUCCESS: 1>, cost: 55.602113, time: -1.000000, additional: {}
2017-05-31 17:14:10:DEBUG:smac.runhistory.runhistory2epm.RunHistory2EPM4Cost:Transform runhistory into X,y format
2017-05-31 17:14:10:DEBUG:smac.optimizer.smbo.SMBO:Search for next configuration

**Comment by mfeurer** [comment]
The configuration space has a bug which prevents it from sampling ordinal hyperparameters. As a hotfix, if you install the latest version from github it should work.

**Comment by mlindauer** [comment]
@mr42 could you please try the dev branch. The issue should be fixed there.
