### ISSUE TITLE
TypeError when using OrdinalHyperparameters

### ISSUE THREAD

**Issue by mr42** [automl/SMAC3#262]
As suggested I checkout the developer branch. My pcs file contains the following:
`x1 real [-5,10] [0]`
`x2 ordinal {0,15} [0]`
When running the branin example with this pcs file I got the following error. When I change the ordinal parameter to a real one no error occurs.

```
python ../../scripts/smac --scenario branin_scenario.txt --verbose DEBUG
INFO:smac.smac_cli.SMACCLI:SMAC call: ../../scripts/smac --scenario branin_scenario.txt --verbose DEBUG
2017-06-01 11:06:33:INFO:smac.scenario.scenario.Scenario:Reading scenario file: branin_scenario.txt
2017-06-01 11:06:33:DEBUG:smac.scenario.scenario.Scenario:Could not parse pcs file with old format; trying new format next
2017-06-01 11:06:33:INFO:smac.scenario.scenario.Scenario:Output to smac3-output_2017-06-01_11:06:33_(038863)
2017-06-01 11:06:33:DEBUG:smac.scenario.scenario.Scenario:Output directory does not exist! Will be created.
2017-06-01 11:06:33:DEBUG:smac.scenario.scenario.Scenario:Writing scenario-file to smac3-output_2017-06-01_11:06:33_(038863)_run1/scenario.txt.
2017-06-01 11:06:33:DEBUG:smac.scenario.scenario.Scenario:Scenario Options:
2017-06-01 11:06:33:DEBUG:smac.scenario.scenario.Scenario:abort_on_first_run_crash = True
2017-06-01 11:06:33:DEBUG:smac.scenario.scenario.Scenario:execdir = .
2017-06-01 11:06:33:DEBUG:smac.scenario.scenario.Scenario:deterministic = True
2017-06-01 11:06:33:DEBUG:smac.scenario.scenario.Scenario:intensification_percentage = 0.5
2017-06-01 11:06:33:DEBUG:smac.scenario.scenario.Scenario:pcs_fn = branin_pcs.pcs
2017-06-01 11:06:33:DEBUG:smac.scenario.scenario.Scenario:run_obj = quality
2017-06-01 11:06:33:DEBUG:smac.scenario.scenario.Scenario:overall_obj = par10
2017-06-01 11:06:33:DEBUG:smac.scenario.scenario.Scenario:cost_for_crash = 2147483647.0
2017-06-01 11:06:33:DEBUG:smac.scenario.scenario.Scenario:algo_runs_timelimit = inf
2017-06-01 11:06:33:DEBUG:smac.scenario.scenario.Scenario:wallclock_limit = inf
2017-06-01 11:06:33:DEBUG:smac.scenario.scenario.Scenario:always_race_default = False
2017-06-01 11:06:33:DEBUG:smac.scenario.scenario.Scenario:ta_run_limit = 500.0
2017-06-01 11:06:33:DEBUG:smac.scenario.scenario.Scenario:minR = 1
2017-06-01 11:06:33:DEBUG:smac.scenario.scenario.Scenario:maxR = 2000
2017-06-01 11:06:33:DEBUG:smac.scenario.scenario.Scenario:output_dir = smac3-output_2017-06-01_11:06:33_(038863)
2017-06-01 11:06:33:DEBUG:smac.scenario.scenario.Scenario:shared_model = False
2017-06-01 11:06:33:DEBUG:smac.scenario.scenario.Scenario:initial_incumbent = DEFAULT
2017-06-01 11:06:33:DEBUG:smac.tae.execute_ta_run_old.ExecuteTARunOld:Calling: python branin.py 0 0 99999999999999.0 0 0 -x1 0.0 -x2 0.0
2017-06-01 11:06:33:DEBUG:smac.tae.execute_ta_run_old.ExecuteTARunOld:Stdout: Result for SMAC: SUCCESS, -1, -1, 55.602113, 0

2017-06-01 11:06:33:DEBUG:smac.tae.execute_ta_run_old.ExecuteTARunOld:Stderr: 
2017-06-01 11:06:33:DEBUG:smac.tae.execute_ta_run_old.ExecuteTARunOld:Return: Status: <StatusType.SUCCESS: 1>, cost: 55.602113, time: -1.000000, additional: {}
2017-06-01 11:06:33:DEBUG:smac.runhistory.runhistory2epm.RunHistory2EPM4Cost:Transform runhistory into X,y format
2017-06-01 11:06:33:DEBUG:smac.optimizer.smbo.SMBO:Search for next configuration
2017-06-01 11:06:33:INFO:smac.stats.stats.Stats:##########################################################
2017-06-01 11:06:33:INFO:smac.stats.stats.Stats:Statistics:
2017-06-01 11:06:33:INFO:smac.stats.stats.Stats:#Incumbent changed: 0
2017-06-01 11:06:33:INFO:smac.stats.stats.Stats:#Target algorithm runs: 1 / 500.0
2017-06-01 11:06:33:INFO:smac.stats.stats.Stats:Used wallclock time: 0.10 / inf sec 
2017-06-01 11:06:33:INFO:smac.stats.stats.Stats:Used target algorithm runtime: -1.00 / inf sec
2017-06-01 11:06:33:DEBUG:smac.stats.stats.Stats:Debug Statistics:
2017-06-01 11:06:33:INFO:smac.stats.stats.Stats:##########################################################
2017-06-01 11:06:33:INFO:smac.facade.smac_facade.SMAC:Final Incumbent: Configuration:
  x1, Value: 0.0
  x2, Value: 0.0

Traceback (most recent call last):
  File "../../scripts/smac", line 20, in <module>
    smac.main_cli()
  File "/home/mrudolph/SMAC3/smac/smac_cli.py", line 99, in main_cli
    optimizer.optimize()
  File "/home/mrudolph/SMAC3/smac/facade/smac_facade.py", line 343, in optimize
    incumbent = self.solver.run()
  File "/home/mrudolph/SMAC3/smac/optimizer/smbo.py", line 122, in run
    challengers = self.choose_next(X, Y)
  File "/home/mrudolph/SMAC3/smac/optimizer/smbo.py", line 224, in choose_next
    self._get_next_by_local_search(init_sls_points)
  File "/home/mrudolph/SMAC3/smac/optimizer/smbo.py", line 294, in _get_next_by_local_search
    configuration, acq_val = self.acq_optimizer.maximize(start_point)
  File "/home/mrudolph/SMAC3/smac/optimizer/local_search.py", line 97, in maximize
    for neighbor in all_neighbors:
  File "/home/mrudolph/anaconda3/lib/python3.6/site-packages/ConfigSpace/util.py", line 113, in get_one_exchange_neighbourhood
    num_neighbors = hp.get_num_neighbors()
TypeError: get_num_neighbors() missing 1 required positional argument: 'value'
```

**Comment by mlindauer** [comment]
Have you also installed the newest version of the ConfigSpace from the repo?

If this does not fix the problem, we have to wait until next week when @mfeurer is back.

**Comment by mr42** [comment]
I cloned the ConfigSpace repo and run succesfully python setup.py install for both ConfigSpace and SMAC3. However I still got the same error.

**Comment by mfeurer** [comment]
If you're still getting the same error there's something wrong with your installation. The latest version of the ConfigSpace on github calls `hp.get_num_neighbors` with a value: https://github.com/automl/ConfigSpace/blob/master/ConfigSpace/util.py#L114

**Comment by mfeurer** [comment]
Just for the record, @smohsinali fixed another bug regarding `OrdinalHyperparameter`. Please pull the latest version from the master branch again.

**Comment by mr42** [comment]
In the moment I have checkout the current development branch of SMAC and the master branch of ConfigSpace. For both SMAC and ConfigSpace I have run python setup.py install. Then I got the following error, when using an ordinal parameter in the branin example:

python ../../scripts/smac --scenario branin_scenario.txt
INFO:smac.smac_cli.SMACCLI:SMAC call: ../../scripts/smac --scenario branin_scenario.txt
INFO:	Reading scenario file: branin_scenario.txt
INFO:	Output to smac3-output_2017-06-07_15:57:02_(227402)
INFO:	##########################################################
INFO:	Statistics:
INFO:	#Incumbent changed: 0
INFO:	#Target algorithm runs: 1 / 500.0
INFO:	Used wallclock time: 0.09 / inf sec 
INFO:	Used target algorithm runtime: -1.00 / inf sec
INFO:	##########################################################
INFO:	Final Incumbent: Configuration:
  x1, Value: 0.0
  x2, Value: 0.0

Traceback (most recent call last):
  File "../../scripts/smac", line 20, in <module>
    smac.main_cli()
  File "/home/mrudolph/SMAC3/smac/smac_cli.py", line 99, in main_cli
    optimizer.optimize()
  File "/home/mrudolph/SMAC3/smac/facade/smac_facade.py", line 343, in optimize
    incumbent = self.solver.run()
  File "/home/mrudolph/SMAC3/smac/optimizer/smbo.py", line 122, in run
    challengers = self.choose_next(X, Y)
  File "/home/mrudolph/SMAC3/smac/optimizer/smbo.py", line 224, in choose_next
    self._get_next_by_local_search(init_sls_points)
  File "/home/mrudolph/SMAC3/smac/optimizer/smbo.py", line 294, in _get_next_by_local_search
    configuration, acq_val = self.acq_optimizer.maximize(start_point)
  File "/home/mrudolph/SMAC3/smac/optimizer/local_search.py", line 97, in maximize
    for neighbor in all_neighbors:
  File "/home/mrudolph/anaconda3/lib/python3.6/site-packages/ConfigSpace/util.py", line 113, in get_one_exchange_neighbourhood
    num_neighbors = hp.get_num_neighbors()
TypeError: get_num_neighbors() missing 1 required positional argument: 'value'

If I checkout the master branch of SMAC I got the following error I already mentioned in a previous issue:

python ../../scripts/smac --scenario branin_scenario.txt
INFO:smac.smac_cli.SMACCLI:SMAC call: ../../scripts/smac --scenario branin_scenario.txt
INFO:smac.scenario.scenario.Scenario:Reading scenario file: branin_scenario.txt
INFO:smac.scenario.scenario.Scenario:Output to smac3-output_2017-06-07_15:59:59_(503076)
index=  1
type=  nan
INFO:smac.stats.stats.Stats:##########################################################
INFO:smac.stats.stats.Stats:Statistics:
INFO:smac.stats.stats.Stats:#Incumbent changed: 0
INFO:smac.stats.stats.Stats:#Target algorithm runs: 1 / 500.0
INFO:smac.stats.stats.Stats:Used wallclock time: 0.09 / inf sec 
INFO:smac.stats.stats.Stats:Used target algorithm runtime: -1.00 / inf sec
INFO:smac.stats.stats.Stats:##########################################################
INFO:smac.facade.smac_facade.SMAC:Final Incumbent: Configuration:
  x1, Value: 0.0
  x2, Value: 0.0

Traceback (most recent call last):
  File "../../scripts/smac", line 20, in <module>
    smac.main_cli()
  File "/home/mrudolph/SMAC3/smac/smac_cli.py", line 86, in main_cli
    optimizer.optimize()
  File "/home/mrudolph/SMAC3/smac/facade/smac_facade.py", line 339, in optimize
    incumbent = self.solver.run()
  File "/home/mrudolph/SMAC3/smac/optimizer/smbo.py", line 123, in run
    challengers = self.choose_next(X, Y)
  File "/home/mrudolph/SMAC3/smac/optimizer/smbo.py", line 184, in choose_next
    self.model.train(X, Y)
  File "/home/mrudolph/SMAC3/smac/epm/base_epm.py", line 94, in train
    return self._train(X, Y)
  File "/home/mrudolph/SMAC3/smac/epm/rf_with_instances.py", line 123, in _train
    data = self.__init_data_container(self.X, self.y)
  File "/home/mrudolph/SMAC3/smac/epm/rf_with_instances.py", line 147, in __init_data_container
    data.set_type_of_feature(i, mn)
  File "/home/mrudolph/anaconda3/lib/python3.6/site-packages/pyrfr/regression.py", line 779, in set_type_of_feature
    return _regression.default_data_container_set_type_of_feature(self, index, type)
TypeError: in method 'default_data_container_set_type_of_feature', argument 3 of type 'unsigned int'

**Comment by AndreBiedenkapp** [comment]
@mr42 Yeah. For this you shouldn't use the SMAC master branch since the fix in #260 is only in the development branch sofar.

**Comment by mfeurer** [comment]
If you compare the traceback you posted with the latest code in the ConfigSpace on github, you will see that it is actually different and the missing argument is there. Therefore, I assume there is something wrong with your installation. You could try pulling the ConfigSpace again and install that (don't forget to uninstall it before), or check whether the ConfigSpace is added to the pythonpath somewhere else.

**Comment by mr42** [comment]
I uninstall ConfigSpace 0.3.2 with pip uninstall ConfigSpace. Afterwards the branin example worked also when I use a ordinal parameter. But strange, that it does work when I uninstall ConfigSpace without reinstalling it afterwards.

**Comment by mfeurer** [comment]
If you do not specify that you want to update the ConfigSpace module and it is already installed, `pip install ConfigSpace` will have no effect. Does SMAC work now as expected?

**Comment by mr42** [comment]
SMAC works now as expected. So I close this issue. If I have problems again I will open a new issue. Thanks a lot for the help.
