### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes

### ISSUE THREAD

**Issue by mlindauer** [automl/SMAC3#274]
Running an AClib2 benchmark and optimizing runtime,
I get some times (very rarely) the following error---see below.
This happens in particular after the TAE has not returned a runtime.
Unfortunately, I cannot reproduce the error locally 
and only from looking at the code, I couldn't figure out how this could happen.
@KEggensperger do you have an idea?

```
Traceback (most recent call last):
  File "/work/ws/nemo/fr_tl1023-aclib-0/aclib2-master/configurators/smac3_warm/scripts/smac", line 20, in <module>
    smac.main_cli()
  File "/work/ws/nemo/fr_tl1023-aclib-0/aclib2-master/configurators/smac3_warm/smac/smac_cli.py", line 79, in main_cli
    optimizer.optimize()
  File "/work/ws/nemo/fr_tl1023-aclib-0/aclib2-master/configurators/smac3_warm/smac/facade/smac_facade.py", line 379, in optimize
    incumbent = self.solver.run()
  File "/work/ws/nemo/fr_tl1023-aclib-0/aclib2-master/configurators/smac3_warm/smac/optimizer/smbo.py", line 118, in run
    X, Y = self.rh2EPM.transform(self.runhistory)
  File "/work/ws/nemo/fr_tl1023-aclib-0/aclib2-master/configurators/smac3_warm/smac/runhistory/runhistory2epm.py", line 216, in transform
    uncensored_X=X, uncensored_y=Y)
  File "/work/ws/nemo/fr_tl1023-aclib-0/aclib2-master/configurators/smac3_warm/smac/epm/rfr_imputator.py", line 115, in impute
    moments='m')
  File "/home/fr/fr_fr/fr_tl1023/anaconda3/lib/python3.5/site-packages/scipy/stats/_distn_infrastructure.py", line 1015, in stats
    mu, mu2, g1, g2 = self._stats(*goodargs)
  File "/home/fr/fr_fr/fr_tl1023/anaconda3/lib/python3.5/site-packages/scipy/stats/_continuous_distns.py", line 4861, in _stats
    mu = (pA - pB) / d   # correction sign
ValueError: operands could not be broadcast together with shapes (23,) (24,) 
```

**Comment by mfeurer** [comment]
How can it happen that the TAE does not return any runtime?

**Comment by mlindauer** [comment]
The TAE wrapper (on the command line) could fail with an uncaught exception.
However, I still don't get why our code does not handle this and how the above error can occur.

**Comment by mfeurer** [comment]
Is this still an open issue?

**Comment by mlindauer** [comment]
I haven't encoutered this bug for quite some time. so closed for now.
