### ISSUE TITLE
master branch fails with latest pyrfr version (0.4.1)

### ISSUE THREAD

**Issue by sfalkner** [automl/SMAC3#277]
Running the auto-sklearn regession example with the master branch and the latest pyrfr version installed I get the following error:
```
[WARNING] [2017-07-09 21:37:23,645:AutoMLSMBO(1)::boston] Could not find meta-data directory /home/sfalkner/repositories/github/auto-sklearn/autosklearn/metalearning/files/r2_regression_dense
Traceback (most recent call last):
  File "HPO_mvn_rectangular_integral.py", line 101, in <module>
    feat_type=feature_types)
  File "/home/sfalkner/repositories/github/auto-sklearn/autosklearn/estimators.py", line 489, in fit
    dataset_name=dataset_name)
  File "/home/sfalkner/repositories/github/auto-sklearn/autosklearn/estimators.py", line 304, in fit
    super(AutoSklearnEstimator, self).fit(*args, **kwargs)
  File "/home/sfalkner/repositories/github/auto-sklearn/autosklearn/estimators.py", line 23, in fit
    self._automl.fit(*args, **kwargs)
  File "/home/sfalkner/repositories/github/auto-sklearn/autosklearn/estimators.py", line 621, in fit
    feat_type=feat_type, dataset_name=dataset_name)
  File "/home/sfalkner/repositories/github/auto-sklearn/autosklearn/automl.py", line 195, in fit
    return self._fit(loaded_data_manager, metric)
  File "/home/sfalkner/repositories/github/auto-sklearn/autosklearn/automl.py", line 449, in _fit
    _proc_smac.run_smbo()
  File "/home/sfalkner/repositories/github/auto-sklearn/autosklearn/smbo.py", line 587, in run_smbo
    seed=1, num_trees=10)
  File "/home/sfalkner/repositories/virtualenvs/autosklearn/lib/python3.4/site-packages/smac-0.5.0-py3.4.egg/smac/epm/rf_with_instances.py", line 81, in __init__
  File "/home/sfalkner/repositories/virtualenvs/autosklearn/lib/python3.4/site-packages/pyrfr/regression.py", line 95, in set_attr
    raise AttributeError("You cannot add attributes to %s" % self)
AttributeError: You cannot add attributes to <pyrfr.regression.forest_opts; proxy of <Swig Object of type 'rfr::forests::forest_options< num_t,response_t,index_t > *' at 0x7f18fcb9bb40> >
```

It fails because the latest version of the forest forbids creating new attributes, and I guess there are some misnamed attributes for the forest_options. The reason I cannot use the version on PiPy (0.4.0) for pyrfr is that it doesn't compile with gcc 5.4.0, a bug fixed in the latest version.

SMAC needs to be updated to use the latest version of the forest (which also has to be put on PiPy) to resolve that issue.

**Comment by mfeurer** [comment]
Does the latest version of pyrfr work with SMAC, i.e. all SMAC unit tests passing? If yes, you could simply upload pyrfr to pypi (following for example [these instructions](http://peterdowns.com/posts/first-time-with-pypi.html)). Then we can easily create a new SMAC bugfix release or maybe even a new SMAC release, given that there are quite a lot of changes since the last release.

**Comment by mlindauer** [comment]
Also running SMAC (dev branch) with the master branch of pyrfr fails.
@AndreBiedenkapp could you please fix this.

**Comment by sfalkner** [comment]
fixed in the latest commit (just one line needed to be changed, no need for a RP)
