### ISSUE TITLE
The 'leadingones' example fails

### ISSUE THREAD

**Issue by loshchil** [automl/SMAC3#286]
https://automl.github.io/SMAC3/stable/manual.html suggests to have a look at the leadingones example
Unfortunately, it outputs the following error:
`NFO:smac.scenario.scenario.Scenario:Output to smac3-output_2017-07-26_15:20:07_(266328)
DEBUG:smac.scenario.scenario.Scenario:Output directory does not exist! Will be created.
DEBUG:smac.scenario.scenario.Scenario:Writing scenario-file to smac3-output_2017-07-26_15:20:07_(266328)_run1/scenario.txt.
Traceback (most recent call last):
File "/home/ilya/Downloads/pycharm-community-2016.3/helpers/pydev/pydevd.py", line 1596, in 
globals = debugger.run(setup['file'], None, None, is_module)
File "/home/ilya/Downloads/pycharm-community-2016.3/helpers/pydev/pydevd.py", line 974, in run
pydev_imports.execfile(file, globals, locals) # execute the script
File "/home/ilya/Downloads/pycharm-community-2016.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
exec(compile(contents+"\n", file, 'exec'), glob, loc)
File "/home/ilya/work/SMAC3/examples/leadingones.py", line 57, in 
"deterministic": "true"
File "/home/ilya/work/SMAC3env/lib/python3.5/site-packages/smac-0.5.0-py3.5.egg/smac/scenario/scenario.py", line 107, in __init__
File "/home/ilya/work/SMAC3env/lib/python3.5/site-packages/smac-0.5.0-py3.5.egg/smac/utils/io/output_writer.py", line 61, in write_scenario_file
File "/home/ilya/work/SMAC3env/lib/python3.5/site-packages/smac-0.5.0-py3.5.egg/smac/utils/io/output_writer.py", line 100, in _parse_argument
File "/home/ilya/work/SMAC3env/lib/python3.5/site-packages/smac-0.5.0-py3.5.egg/smac/utils/io/output_writer.py", line 169, in write_pcs_file
File "/home/ilya/work/SMAC3env/lib/python3.5/site-packages/ConfigSpace/io/pcs.py", line 329, in write
condition_lines.write(build_condition(condition))
File "/home/ilya/work/SMAC3env/lib/python3.5/site-packages/ConfigSpace/io/pcs.py", line 124, in build_condition
", ".join(condition.values))
TypeError: sequence item 0: expected str instance, int found`

**Comment by mlindauer** [comment]
Already fixed in Dev Branch.
