### ISSUE TITLE
TypeError: validate() got an unexpected keyword argument 'output

### ISSUE THREAD

**Issue by yujiezeng** [automl/SMAC3#392]
I've got the following error when I use optimizer.validate(), I think line 299 in sbmo.py should be `output_fn=new_rh_path` ?
```
Traceback (most recent call last):
  File "../../../../SMAC3/scripts/smac", line 20, in <module>
    smac.main_cli()
  File "/home/SMAC3/smac/smac_cli.py", line 129, in main_cli
    optimizer.validate()
  File "/home/SMAC3/smac/facade/smac_facade.py", line 446, in validate
    use_epm, n_jobs, backend)
  File "/home/SMAC3/smac/optimizer/smbo.py", line 299, in validate
    output=new_rh_path)
TypeError: validate() got an unexpected keyword argument 'output'
```

**Comment by mfeurer** [comment]
Thanks a lot for reporting this. I think this was fixed in #378.
