### ISSUE TITLE
SMAC does not gracefully handle exceptions if `use_pynisher=False`

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#437]
```
/home/feurerm/projects/2018_nips_working_paper/2018_nips_working_paper/metalearning/greedy_portfolio.py:683: RuntimeWarning: invalid value encountered in greater_equal
  np.all((normalized_matrix >= 0) | (~np.isfinite(normalized_matrix)))
/home/feurerm/projects/2018_nips_working_paper/2018_nips_working_paper/metalearning/greedy_portfolio.py:684: RuntimeWarning: invalid value encountered in less_equal
  and np.all((normalized_matrix <= 1) | (~np.isfinite(normalized_matrix)))
/home/feurerm/projects/2018_nips_working_paper/2018_nips_working_paper/metalearning/resampling_strategies.py:233: RuntimeWarning: invalid value encountered in less
  loc = len(lc_runtime[(lc_runtime < cutoff) == True]) - 1
Traceback (most recent call last):
  File "/home/feurerm/environments/2018_nips_working_paper/envs/2018_nips_working_paper/lib/python3.6/site-packages/smac/intensification/intensification.py", line 162, in intensify
    self._add_inc_run(incumbent=incumbent, run_history=run_history)
  File "/home/feurerm/environments/2018_nips_working_paper/envs/2018_nips_working_paper/lib/python3.6/site-packages/smac/intensification/intensification.py", line 263, in _add_inc_run
    instance_specific=self.instance_specifics.get(next_instance, "0"))
  File "/home/feurerm/environments/2018_nips_working_paper/envs/2018_nips_working_paper/lib/python3.6/site-packages/smac/tae/execute_ta_run.py", line 154, in start
    "Skip target algorithm run due to exhausted "
smac.tae.execute_ta_run.BudgetExhaustedException: Skip target algorithm run due to exhausted configuration budget

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/feurerm/mhome/projects/2018_nips_working_paper/2018_nips_working_paper/scripts/run_metalearning.py", line 133, in <module>
    automl=automl,
  File "/home/feurerm/projects/2018_nips_working_paper/2018_nips_working_paper/metalearning/util.py", line 177, in evaluate_performance
    portfolio_size=portfolio_size)
  File "/home/feurerm/projects/2018_nips_working_paper/2018_nips_working_paper/metalearning/global_portfolio.py", line 522, in build
    losses=losses,
  File "/home/feurerm/projects/2018_nips_working_paper/2018_nips_working_paper/metalearning/global_portfolio.py", line 441, in build
    portfolio_builder.optimize_portfolio_with_pils(greedy_init=self.greedy_init)
  File "/home/feurerm/projects/2018_nips_working_paper/2018_nips_working_paper/metalearning/global_portfolio.py", line 326, in optimize_portfolio_with_pils
    cutoffs=init_cutoffs,
  File "/home/feurerm/projects/2018_nips_working_paper/2018_nips_working_paper/metalearning/global_portfolio.py", line 268, in _optimize_portfolio_with_pils
    incumbent = epils.optimize()
  File "/home/feurerm/environments/2018_nips_working_paper/envs/2018_nips_working_paper/lib/python3.6/site-packages/smac/facade/epils_facade.py", line 364, in optimize
    incumbent = self.solver.run()
  File "/home/feurerm/environments/2018_nips_working_paper/envs/2018_nips_working_paper/lib/python3.6/site-packages/smac/optimizer/epils.py", line 191, in run
    local_inc = self.local_search(start_point=start_point)
  File "/home/feurerm/environments/2018_nips_working_paper/envs/2018_nips_working_paper/lib/python3.6/site-packages/smac/optimizer/epils.py", line 283, in local_search
    log_traj=False)
  File "/home/feurerm/environments/2018_nips_working_paper/envs/2018_nips_working_paper/lib/python3.6/site-packages/smac/intensification/intensification.py", line 182, in intensify
    inc_perf = run_history.get_cost(incumbent)
  File "/home/feurerm/environments/2018_nips_working_paper/envs/2018_nips_working_paper/lib/python3.6/site-packages/smac/runhistory/runhistory.py", line 271, in get_cost
    config_id = self.config_ids[config]
KeyError: Configuration:
  cutoff_1, Value: 1
  cutoff_10, Value: 32
  cutoff_11, Value: 181
  cutoff_12, Value: 2
  cutoff_13, Value: 1
  cutoff_14, Value: 2
  cutoff_15, Value: 45
  cutoff_16, Value: 32
  cutoff_2, Value: 6491
  cutoff_3, Value: 512
  cutoff_4, Value: 181
  cutoff_5, Value: 11
  cutoff_6, Value: 512
  cutoff_7, Value: 2
  cutoff_8, Value: 156
  cutoff_9, Value: 2
  portfolio_member_1, Value: 326
  portfolio_member_10, Value: 476
  portfolio_member_11, Value: 76
  portfolio_member_12, Value: 714
  portfolio_member_13, Value: 446
  portfolio_member_14, Value: 81
  portfolio_member_15, Value: 430
  portfolio_member_16, Value: 31
  portfolio_member_2, Value: 264
  portfolio_member_3, Value: 763
  portfolio_member_4, Value: 699
  portfolio_member_5, Value: 785
  portfolio_member_6, Value: 548
  portfolio_member_7, Value: 318
  portfolio_member_8, Value: 620
  portfolio_member_9, Value: 348
  resampling_strategy, Value: 'cv:5'
```

**Comment by mfeurer** [comment]
This will be fixed in an upcoming release via #534.
