### ISSUE TITLE
json serialization bug

### ISSUE THREAD

**Issue by fayeshine** [automl/SMAC3#451]
Traceback (most recent call last):
 File "/home/wenjian/anaconda3/lib/python3.6/site-packages/smac/facade/smac_facade.py", line 400, in optimize
   incumbent = self.solver.run()
 File "/home/wenjian/anaconda3/lib/python3.6/site-packages/smac/optimizer/smbo.py", line 196, in run
   output_directory=self.scenario.output_dir_for_this_run)
 File "/home/wenjian/anaconda3/lib/python3.6/site-packages/smac/optimizer/pSMAC.py", line 83, in write
   run_history.save_json(temporary_filename, save_external=False)
 File "/home/wenjian/anaconda3/lib/python3.6/site-packages/smac/runhistory/runhistory.py", line 333, in save_json
   "configs": configs}, fp, cls=EnumEncoder)
 File "/home/wenjian/anaconda3/lib/python3.6/json/__init__.py", line 179, in dump
   for chunk in iterable:
 File "/home/wenjian/anaconda3/lib/python3.6/json/encoder.py", line 430, in _iterencode
   yield from _iterencode_dict(o, _current_indent_level)
 File "/home/wenjian/anaconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
   yield from chunks
 File "/home/wenjian/anaconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
   yield from chunks
 File "/home/wenjian/anaconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
   yield from chunks
 File "/home/wenjian/anaconda3/lib/python3.6/json/encoder.py", line 437, in _iterencode
   o = _default(o)
 File "/home/wenjian/anaconda3/lib/python3.6/site-packages/smac/runhistory/runhistory.py", line 38, in default
   return json.JSONEncoder.default(self, obj)
 File "/home/wenjian/anaconda3/lib/python3.6/json/encoder.py", line 180, in default
   o.__class__.__name__)
TypeError: Object of type 'function' is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "<ipython-input-1-ccf0947de573>", line 352, in nn_smac
   incumbent = smac.optimize()
 File "/home/wenjian/anaconda3/lib/python3.6/site-packages/smac/facade/smac_facade.py", line 410, in optimize
   fn=os.path.join(self.output_dir, "runhistory.json")
 File "/home/wenjian/anaconda3/lib/python3.6/site-packages/smac/runhistory/runhistory.py", line 333, in save_json
   "configs": configs}, fp, cls=EnumEncoder)
 File "/home/wenjian/anaconda3/lib/python3.6/json/__init__.py", line 179, in dump
   for chunk in iterable:
 File "/home/wenjian/anaconda3/lib/python3.6/json/encoder.py", line 430, in _iterencode
   yield from _iterencode_dict(o, _current_indent_level)
 File "/home/wenjian/anaconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
   yield from chunks
 File "/home/wenjian/anaconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
   yield from chunks
 File "/home/wenjian/anaconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
   yield from chunks
 File "/home/wenjian/anaconda3/lib/python3.6/json/encoder.py", line 437, in _iterencode
   o = _default(o)
 File "/home/wenjian/anaconda3/lib/python3.6/site-packages/smac/runhistory/runhistory.py", line 38, in default
   return json.JSONEncoder.default(self, obj)
 File "/home/wenjian/anaconda3/lib/python3.6/json/encoder.py", line 180, in default
   o.__class__.__name__)
TypeError: Object of type 'function' is not JSON serializable

**Comment by mlindauer** [comment]
Hi Wenjian,

Thanks for reporting this issue. Unfortunately, we cannot reproduce the issue without a small toy example triggering the bug. Could you please provide such an example.

Best regards,
Marius Lindauer

**Comment by fayeshine** [comment]
@mlindauer I found the problem，I used 'function' as parameter and this function cannot be serialized by JSON, so when dump runhistory it crashed.

**Comment by mlindauer** [comment]
Great.
