### ISSUE TITLE
Maximum length of Categorical Hyperparameter

### ISSUE THREAD

**Issue by VinceDT** [automl/SMAC3#504]
#### Description
When the length of a categorical hyperparameter longer than 128 a runtime error is thrown from pyrfr. 
Can this threshold be adapted? And would it even make sense?

Thanks!

#### Actual Results
```
Traceback (most recent call last):
  File "/export/home/ladmin/Testspace/pysmac_test/conditionals_test.py", line 125, in <module>
    incumbent = smac.optimize()
  File "/export/home/ladmin/datasets_local/virtual_envs/pysmac_py3_venv/lib/python3.5/site-packages/smac/facade/smac_facade.py", line 489, in optimize
    incumbent = self.solver.run()
  File "/export/home/ladmin/datasets_local/virtual_envs/pysmac_py3_venv/lib/python3.5/site-packages/smac/optimizer/smbo.py", line 203, in run
    challengers = self.choose_next(X, Y)
  File "/export/home/ladmin/datasets_local/virtual_envs/pysmac_py3_venv/lib/python3.5/site-packages/smac/optimizer/smbo.py", line 265, in choose_next
    self.model.train(X, Y)
  File "/export/home/ladmin/datasets_local/virtual_envs/pysmac_py3_venv/lib/python3.5/site-packages/smac/epm/base_epm.py", line 141, in train
    return self._train(X, Y)
  File "/export/home/ladmin/datasets_local/virtual_envs/pysmac_py3_venv/lib/python3.5/site-packages/smac/epm/rf_with_instances.py", line 146, in _train
    self.rf.fit(data, rng=self.rng)
  File "/export/home/ladmin/datasets_local/virtual_envs/pysmac_py3_venv/lib/python3.5/site-packages/pyrfr/regression.py", line 2441, in fit
    return _regression.binary_rss_forest_fit(self, data, rng)
RuntimeError: bitset::set: __position (which is 128) >= _Nb (which is 128)
```
#### Versions
0.10

**Comment by mlindauer** [comment]
That's an interesting observation. 
What is the unit here? 128 byte, characters, ...?

Sorry for asking you again the same thing, but could you please re-open this issue again in the pyrfr repo? The developer of the pyrfr does not read the SMAC issue tracker.

https://github.com/automl/random_forest_run

Cheers,
Marius
