### ISSUE TITLE
Initial design fails with GreaterThanCondition

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#531]
Example code to reproduce:

```
import numpy as np
import sklearn.datasets
import sklearn.metrics
from sklearn.neural_network import MLPClassifier

from ConfigSpace import (
    UniformIntegerHyperparameter,
    CategoricalHyperparameter,
    GreaterThanCondition,
    ConfigurationSpace,
    UniformFloatHyperparameter,
)

from smac.scenario.scenario import Scenario
from smac.facade.smac_hpo_facade import SMAC4HPO


cs = ConfigurationSpace()
alpha = UniformFloatHyperparameter(
    name='alpha', lower=0.000001, upper=1, default_value=0.0001, log=True,
)
lrate = UniformFloatHyperparameter(
    name='lrate', lower=0.000001, upper=1, default_value=0.001, log=True,
)
momentum = UniformFloatHyperparameter(
    name='momentum', lower=0.5, upper=1, default_value=0.9,
)
n_layers = UniformIntegerHyperparameter(
    name='n_layers', lower=1, upper=3,
)
number_neurons_1 = UniformIntegerHyperparameter(
    name='neurons_1', lower=16, upper=256, default_value=32, log=True,
)
number_neurons_2 = UniformIntegerHyperparameter(
    name='neurons_2', lower=16, upper=256, default_value=32, log=True,
)
number_neurons_3 = UniformIntegerHyperparameter(
    name='neurons_3', lower=16, upper=256, default_value=32, log=True,
)
lrate_schedule = CategoricalHyperparameter(
    name='lrate_schedule', choices=['constant', 'invscaling', 'adaptive'],
)
cs.add_hyperparameters([
    alpha, lrate, momentum, number_neurons_1, number_neurons_2,
    number_neurons_3, n_layers, lrate_schedule,
])
neurons_2_condition = GreaterThanCondition(number_neurons_2, n_layers, 1)
neurons_3_condition = GreaterThanCondition(number_neurons_3, n_layers, 2)
cs.add_conditions([neurons_2_condition, neurons_3_condition])


# Load data
X, y = sklearn.datasets.load_breast_cancer(return_X_y=True)
X_train, X_valid, y_train, y_valid = \
        sklearn.model_selection.train_test_split(X, y, random_state=1)


def eval_mlp(config, seed):
    n_layers = config['n_layers']
    layer_sizes = []
    for i in range(1, n_layers + 1):
        layer_sizes.append(config['neurons_%d' % i])
    layer_sizes = tuple(layer_sizes)

    mlp = MLPClassifier(
        hidden_layer_sizes=layer_sizes,
        activation='relu',
        solver='sgd',
        alpha=config['alpha'],
        learning_rate=config['lrate_schedule'],
        learning_rate_init=config['lrate'],
        momentum=config['momentum'],
        warm_start=False,
        random_state=seed,
    )

    classes = np.unique(y_train)
    mlp.fit(X_train, y_train)

    return 1 - mlp.score(X_valid, y_valid)


scenario = Scenario({
    "run_obj": "quality",   # we optimize quality (alternatively runtime)
    "runcount-limit": 200,  # maximum function evaluations
    "cs": cs,               # configuration space
    "deterministic": "false"
})

smac = SMAC4HPO(
    scenario=scenario,
    rng=np.random.RandomState(42),
    tae_runner=eval_mlp,
    intensifier_kwargs={'maxR': 4},
)

incumbent = smac.optimize()
```
output is:
```
/home/feurerm/miniconda/3-4.5.4/envs/smac3/bin/python3 /home/feurerm/sync_dir/projects/smac3/bug.py
INFO:smac.utils.io.cmd_reader.CMDReader:Output to smac3-output_2019-09-11_16:32:34_527224
INFO:smac.initial_design.sobol_design.SobolDesign:Running initial design for 50 configurations
INFO:smac.facade.smac_hpo_facade.SMAC4HPO:<class 'smac.facade.smac_hpo_facade.SMAC4HPO'>
INFO:smac.stats.stats.Stats:##########################################################
INFO:smac.stats.stats.Stats:Statistics:
INFO:smac.stats.stats.Stats:#Incumbent changed: -1
INFO:smac.stats.stats.Stats:#Target algorithm runs: 0 / 200.0
INFO:smac.stats.stats.Stats:#Configurations: 0
INFO:smac.stats.stats.Stats:Used wallclock time: 0.01 / inf sec 
INFO:smac.stats.stats.Stats:Used target algorithm runtime: 0.00 / inf sec
INFO:smac.stats.stats.Stats:##########################################################
INFO:smac.facade.smac_hpo_facade.SMAC4HPO:Final Incumbent: None
Traceback (most recent call last):
  File "/home/feurerm/sync_dir/projects/smac3/bug.py", line 97, in <module>
    incumbent = smac.optimize()
  File "/home/feurerm/sync_dir/projects/smac3/smac/facade/smac_ac_facade.py", line 542, in optimize
    incumbent = self.solver.run()
  File "/home/feurerm/sync_dir/projects/smac3/smac/optimizer/smbo.py", line 186, in run
    self.start()
  File "/home/feurerm/sync_dir/projects/smac3/smac/optimizer/smbo.py", line 157, in start
    self.incumbent = self.initial_design.run()
  File "/home/feurerm/sync_dir/projects/smac3/smac/initial_design/initial_design.py", line 116, in run
    configs = self.select_configurations()
  File "/home/feurerm/sync_dir/projects/smac3/smac/initial_design/initial_design.py", line 101, in select_configurations
    return self._select_configurations()
  File "/home/feurerm/sync_dir/projects/smac3/smac/initial_design/sobol_design.py", line 50, in _select_configurations
    cs=cs)
  File "/home/feurerm/sync_dir/projects/smac3/smac/initial_design/initial_design.py", line 220, in _transform_continuous_designs
    vector=vector)
  File "ConfigSpace/util.py", line 325, in ConfigSpace.util.deactivate_inactive_hyperparameters
  File "ConfigSpace/configuration_space.py", line 1067, in ConfigSpace.configuration_space.Configuration.__init__
  File "ConfigSpace/configuration_space.py", line 1093, in ConfigSpace.configuration_space.Configuration.is_valid_configuration
  File "ConfigSpace/c_util.pyx", line 38, in ConfigSpace.c_util.check_configuration
  File "ConfigSpace/c_util.pyx", line 134, in ConfigSpace.c_util.check_configuration
ValueError: Inactive hyperparameter 'neurons_2' must not be specified, but has the vector value: '0.24699765174986646'.

Process finished with exit code 1
```

**Comment by mlindauer** [comment]
Thanks for reporting.

That looks like it is a bug in the configspace (util.deactivate_inactive_hyperparameters). However, it is not obvious to me where exactly the bug is. Nevertheless, I think it should be an issue in the issue tracker of the configspace.

**Comment by mfeurer** [comment]
Closing this as it appears that this is indeed an issue with the ConfigSpace.

**Comment by PhMueller** [comment]
A possible workaournd: 

Instead of writing:  
```
            try:
                conf = deactivate_inactive_hyperparameters(
                    configuration=None, configuration_space=configspace, vector=vector
                )
            except ForbiddenValueError:
                continue
```
cast it to a configuration before: 
```
            try:
                config_from_vec = CS.Configuration(configspace, vector=vector)	
                conf = deactivate_inactive_hyperparameters(
                    configuration=config_from_vec, configuration_space=configspace, vector=None
                )
            except ForbiddenValueError:
                continue
```

See also in this fork here: https://github.com/automl/SMAC3/commit/88fe6e8a19d40a53be00ef4a0bfd6c703e3aafc0
