### ISSUE TITLE
'First configuration crashes' even though target function callable is never called

### ISSUE THREAD

**Issue by gamer01** [automl/SMAC3#546]
#### Description

Because of #545 i can't say for sure if it also happens in other configurations. I am happy to get smac running in any config. The issue is minor as there is a good workarround. The first configuration always crashes, even though my code is never called.

#### Steps/Code to Reproduce
```python
from functools import partial

import numpy as np
import pandas as pd
from ConfigSpace import CategoricalHyperparameter
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
from smac.configspace import ConfigurationSpace
from smac.facade.smac_bo_facade import SMAC4BO
from smac.scenario.scenario import Scenario


def eval(cfg, X, y) -> float:
    cfg = dict(cfg)

    clf = Pipeline([('vec', TfidfVectorizer()), LinearSVC())])
    clf.set_params(**cfg)

    scores = cross_val_score(clf, X, y, cv=5)
    return 1 - scores.mean()  # Minimize!


if __name__ == '__main__':
    df = pd.read_hdf('data/chat.h5', 'df')

    evaluation = partial(eval, X=df.msg, y=df.author)

    cs = ConfigurationSpace()
    cs.add_hyperparameters([CategoricalHyperparameter('vec__analyzer', ['word', 'char_wb'], default_value='char_wb'),
                            CategoricalHyperparameter('vec__lowercase', [True, False], default_value=True)])
    scenario = Scenario({"run_obj": "quality",  # we optimize quality (alternatively runtime)
                         "runcount-limit": 2,
                         # max. number of function evaluations; for this example set to a low number
                         "cs": cs,  # configuration space
                         "deterministic": "true",
                         'abort_on_first_run_crash': False
                         })
    smac = SMAC4BO(scenario=scenario, rng=np.random.RandomState(42),
                   tae_runner=evaluation)
    incumbent = smac.optimize()

    inc_value = evaluation(incumbent)
    print("Optimized Value: %.2f" % (inc_value))
```

#### Expected Results

Run properly

#### Actual Results

First configuration of `SMAC4BO` fails. When i set breakpoints inside my evaluationfunction, i can see, that my function has not even been called!

```
INFO:smac.initial_design.sobol_design.SobolDesign:Running initial design for 1 configurations
INFO:smac.facade.smac_bo_facade.SMAC4BO:<class 'smac.facade.smac_bo_facade.SMAC4BO'>
Process pynisher function call:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/site-packages/pynisher/limit_function_call.py", line 93, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
TypeError: eval() got an unexpected keyword argument 'seed'
Process pynisher function call:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/site-packages/pynisher/limit_function_call.py", line 93, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
TypeError: eval() got an unexpected keyword argument 'seed'
```
#### Workaround
- Adding `'abort_on_first_run_crash': False` to my `Scenario` object. This makes SMAC run properly and only print the error to commandline.
- Disabling pynisher `smac.solver.intensifier.tae_runner.use_pynisher = False` makes SMAC **crash anyways** as the error is not catched.

#### Versions

0.11.1

**Comment by gamer01** [comment]
The evaluation results are unexpected. i am not so sure anymore if my function is even used. Meanwhile i found out that the function `eval` is not the python builtin, but my target-function. Obvoiusly smac tries to pass a couple of additonal **kwargs to my function ('seed', 'instance'). I could not find anything about that in the documentation. The target-function from the quickrun also has only 1 argument!

adding `**kwargs` to my target-function definition solves the issue and the optimizer acutally runs properly.

All in all it seems to be an issue in the documentation

```python
def eval(cfg, X, y, **kwargs) -> float:
    cfg = dict(cfg)

    clf = Pipeline([('vec', TfidfVectorizer()), ('svm', LinearSVC())])
    clf.set_params(**cfg)

    scores = cross_val_score(clf, X, y, cv=5)
    return 1 - scores.mean()  # Minimize!
```
