### ISSUE TITLE
GP breaks with sklearn>=0.22

### ISSUE THREAD

**Issue by AndreBiedenkapp** [automl/SMAC3#566]
sklearn >= 0.22 breaks the GP with the follwoing error message in our unit-tests:

```
ERROR: test_train_continue_on_linalg_error_2 (test.test_epm.test_gp.TestGP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/testenv/lib/python3.5/unittest/mock.py", line 1159, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/automl/SMAC3/test/test_epm/test_gp.py", line 240, in test_train_continue_on_linalg_error_2
    model._train(X[:10], Y[:10], do_optimize=True)
  File "/home/travis/build/automl/SMAC3/smac/epm/gaussian_process.py", line 116, in _train
    self.gp.fit(X, y)
  File "/home/travis/miniconda/envs/testenv/lib/python3.5/site-packages/skopt/learning/gaussian_process/gpr.py", line 195, in fit
    super(GaussianProcessRegressor, self).fit(X, y)
  File "/home/travis/miniconda/envs/testenv/lib/python3.5/site-packages/sklearn/gaussian_process/_gpr.py", line 255, in fit
    clone_kernel=False)
  File "/home/travis/miniconda/envs/testenv/lib/python3.5/unittest/mock.py", line 919, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/home/travis/miniconda/envs/testenv/lib/python3.5/unittest/mock.py", line 985, in _mock_call
    ret_val = effect(*args, **kwargs)
TypeError: __call__() got an unexpected keyword argument 'clone_kernel'
```

With the acceptance of PR #565 we require 0.22 > sklearn >= 0.18.2

**Comment by mfeurer** [comment]
Fixed in #602.
