### ISSUE TITLE
Installation issue with lazy_import

### ISSUE THREAD

**Issue by PieterLeyman** [automl/SMAC3#639]
#### Description
When trying to install SMAC3 in Python for the first time, either via pip or manually, I receive a nasty-looking error with regards to lazy_import:

ERROR: Command errored out with exit status 1:     
                                                                                                                                                                 command: /home/leyman/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bim68v8t/lazy-import/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bim68v8t/lazy-import/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-bim68v8t/lazy-import/pip-egg-info                                                                                                                                                                                           

cwd: /tmp/pip-install-bim68v8t/lazy-import/                                                                                                                                                                   

Complete output (7 lines):                                                                                                                                                                                    Traceback (most recent call last):          
                                                                                                                                                                           
File "<string>", line 1, in module    
                                                                                                                                                                          File "/tmp/pip-install-bim68v8t/lazy-import/setup.py", line 6, in <module>                                                                                                                                           readme = infile.read()               
                                                                                                                                                                            File "/home/leyman/anaconda3/lib/python3.6/encodings/ascii.py", line 26, in decode                                                                                                                                   return codecs.ascii_decode(input, self.errors)[0] 

I should mention that I am trying to install SMAC on a supercomputer (the grace cluster of Holger Hoos' group), and that colleagues of mine seem to have no issue with installing lazy_import. So my question is, have you ever had an issue like this before? 

As far as I can tell, something might have gone wrong with my conda installation and this is not a SMAC issue, though other packages seem to work just fine. If nothing else works, I will reinstal Anaconda, but since I use other packages as well, I would like to try and avoid this if at all possible. So, I would greatly appreciate if you could let me know whether you have ever encountered this issue with SMAC before or not.

I am aware of the possible issue with swig, but I managed to solve it by first installing that package.

Lastly, the same error occurs when trying install the pyImp package, which also requires lazy_import.

#### Steps/Code to Reproduce
No idea, since it works just fine for colleagues of mine

#### Expected Results
Successfully install SMAC

#### Actual Results
Installation failed 

#### Versions
SMAC version 3, pyImp 1.1.0

**Comment by PieterLeyman** [comment]
For whatever reason, it seems to work now at try #1251

**Comment by PieterLeyman** [comment]
Should anyone have the same issue:
1) Create new conda environment, activate it
2) pip install lazy_import
3) conda install swig
4) pip install SMAC

The order of steps 2 and 3 appears to be crucial.
