### ISSUE TITLE
AttributeError: '_SuccessiveHalving' object has no attribute 'stage'

### ISSUE THREAD

**Issue by KEggensperger** [automl/SMAC3#695]
#### Description
Run BOHB4HPO in parallel

#### Steps/Code to Reproduce
Move these files into the example directory:
[no_stage_exception.zip](https://github.com/automl/SMAC3/files/5342290/no_stage_exception.zip)

Then run:
```python BOHB4HPO_sgd_instances.py```

#### Expected Results
Should run w/o errors

#### Actual Results
After 7 seconds it fails with this error:
```
INFO:smac.facade.smac_bohb_facade.BOHB4HPO:Estimated cost of incumbent: 2147483647.000000
Traceback (most recent call last):
  File "BOHB4HPO_sgd_instances.py", line 79, in <module>
    main()
  File "BOHB4HPO_sgd_instances.py", line 75, in main
    incumbent = smac.optimize()
  File "/home/eggenspk/Work/git/SMAC3/smac/facade/smac_ac_facade.py", line 597, in optimize
    incumbent = self.solver.run()
  File "/home/eggenspk/Work/git/SMAC3/smac/optimizer/smbo.py", line 278, in run
    self._incorporate_run_results(run_info, result, time_left)
  File "/home/eggenspk/Work/git/SMAC3/smac/optimizer/smbo.py", line 481, in _incorporate_run_results
    result=result,
  File "/home/eggenspk/Work/git/SMAC3/smac/intensification/parallel_scheduling.py", line 256, in process_results
    log_traj=log_traj,
  File "/home/eggenspk/Work/git/SMAC3/smac/intensification/hyperband.py", line 169, in process_results
    log_traj=log_traj)
  File "/home/eggenspk/Work/git/SMAC3/smac/intensification/successive_halving.py", line 340, in process_results
    curr_budget = self.all_budgets[self.stage]
AttributeError: '_SuccessiveHalving' object has no attribute 'stage'
```

#### Versions
0.13.0

**Comment by mfeurer** [comment]
Fixed via #700.
