### ISSUE TITLE
ValueError: Cannot compare configs that were run on different instances-seeds-budgets

### ISSUE THREAD

**Issue by KEggensperger** [automl/SMAC3#696]
#### Description
Run SMAC4BOHB using instances as budgets in parallel, could be related to #695. The main differences to code provided with #695 are the configuration space, the instance names and a higher cutoff per run.

#### Steps/Code to Reproduce
Move these files into the example directory:
[cannot_compare.zip](https://github.com/automl/SMAC3/files/5346334/cannot_compare.zip)

Then run:
python BOHB4HPO_sgd_instances.py

( I observed some randomness, but the exception was raised reliably)

#### Expected Results
```
Traceback (most recent call last):
  File "BOHB4HPO_sgd_instances.py", line 83, in <module>
    main(seed=seed)
  File "BOHB4HPO_sgd_instances.py", line 77, in main
    incumbent = smac.optimize()
  File "/home/eggenspk/Work/git/SMAC3/smac/facade/smac_ac_facade.py", line 597, in optimize
    incumbent = self.solver.run()
  File "/home/eggenspk/Work/git/SMAC3/smac/optimizer/smbo.py", line 278, in run
    self._incorporate_run_results(run_info, result, time_left)
  File "/home/eggenspk/Work/git/SMAC3/smac/optimizer/smbo.py", line 481, in _incorporate_run_results
    result=result,
  File "/home/eggenspk/Work/git/SMAC3/smac/intensification/parallel_scheduling.py", line 256, in process_results
    log_traj=log_traj,
  File "/home/eggenspk/Work/git/SMAC3/smac/intensification/hyperband.py", line 169, in process_results
    log_traj=log_traj)
  File "/home/eggenspk/Work/git/SMAC3/smac/intensification/successive_halving.py", line 388, in process_results
    self._update_stage(run_history=run_history)
  File "/home/eggenspk/Work/git/SMAC3/smac/intensification/successive_halving.py", line 640, in _update_stage
    k=next_n_chal)
  File "/home/eggenspk/Work/git/SMAC3/smac/intensification/successive_halving.py", line 887, in _top_k
    % (run_key, cur_run_key)
ValueError: Cannot compare configs that were run on different instances-seeds-budgets: [InstSeedBudgetKey(instance='189908_10MIN_logloss', seed=0, budget=0.0), InstSeedBudgetKey(instance='189909_10MIN_logloss', seed=0, budget=0.0)] vs [InstSeedBudgetKey(instance='189909_10MIN_logloss', seed=0, budget=0.0)]
```

#### Actual Results
Runs w/o errors

#### Versions
smac==0.13.0

And some more, that could be relevant:
scipy==1.5.1
numpy==1.19.0
dask==2.30.0
ConfigSpace==0.4.15
scikit-learn==0.23.1

**Comment by mfeurer** [comment]
Should be fixed by merging #709
