### ISSUE TITLE
[Question] How to make pSMAC work with examples/SMAC4HPO_svm.py 

### ISSUE THREAD

**Issue by mh415-f** [automl/SMAC3#713]
#### Description
I want to use pSMAC in a cluster environment and tried to make the small SVM example in `examples/SMAC4HPO_svm.py` work in parallel. Unfortunately, this didn't work.

#### Steps/Code to Reproduce
I took `examples/SMAC4HPO_svm.py` and only added the line `"shared_model": True` to the kwargs of the Scenario object. Then I ran the script twice at once.

#### Expected Results
Both pSMAC instances working together and sharing information.

#### Actual Results
```
/home/user/anaconda3/envs/myenv/lib/python3.8/site-packages/pyparsing.py:3190: FutureWarning: Possible set intersection at position 3
  self.re = re.compile(self.reString)
INFO:smac.utils.io.cmd_reader.CMDReader:Output to smac3-output_2020-12-16_12:22:46_196727
Default Value: 0.03
Optimizing! Depending on your machine, this might take a few minutes.
INFO:smac.facade.smac_hpo_facade.SMAC4HPO:Optimizing a deterministic scenario for quality without a tuner timeout - will make SMAC deterministic and only evaluate one configuration per iteration!
INFO:smac.initial_design.sobol_design.SobolDesign:Running initial design for 50 configurations
INFO:smac.facade.smac_hpo_facade.SMAC4HPO:<class 'smac.facade.smac_hpo_facade.SMAC4HPO'>
INFO:smac.optimizer.smbo.SMBO:Running initial design
INFO:smac.optimizer.smbo.SMBO:Shared model mode: Finished loading new runs, found 200 new runs.
INFO:smac.intensification.intensification.Intensifier:First run, no incumbent provided; challenger is assumed to be the incumbent
INFO:smac.intensification.intensification.Intensifier:Challenger (0.0467) is better than incumbent (0.0733) on 1 runs.
INFO:smac.intensification.intensification.Intensifier:Changes in incumbent:
INFO:smac.intensification.intensification.Intensifier:  C : 500.0005 -> 750.00025
INFO:smac.intensification.intensification.Intensifier:  gamma : 'value' -> 'auto'
INFO:smac.intensification.intensification.Intensifier:  kernel : 'poly' -> 'rbf'
INFO:smac.optimizer.smbo.SMBO:Shared model mode: Finished loading new runs, found 0 new runs.
INFO:smac.stats.stats.Stats:##########################################################
INFO:smac.stats.stats.Stats:Statistics:
INFO:smac.stats.stats.Stats:#Incumbent changed: 0
INFO:smac.stats.stats.Stats:#Submitted target algorithm runs: 0 / 200.0
INFO:smac.stats.stats.Stats:#Finished target algorithm runs: 0 / 200.0
INFO:smac.stats.stats.Stats:#Configurations: 0
INFO:smac.stats.stats.Stats:Used wallclock time: 0.10 / inf sec 
INFO:smac.stats.stats.Stats:Used target algorithm runtime: 0.00 / inf sec
INFO:smac.stats.stats.Stats:##########################################################
INFO:smac.facade.smac_hpo_facade.SMAC4HPO:Final Incumbent: None
Traceback (most recent call last):
  File "/home/user/code/test/run_smac.py", line 114, in <module>
    incumbent = smac.optimize()
  File "/home/user/anaconda3/envs/myenv/lib/python3.8/site-packages/smac/facade/smac_ac_facade.py", line 597, in optimize
    incumbent = self.solver.run()
  File "/home/user/anaconda3/envs/myenv/lib/python3.8/site-packages/smac/optimizer/smbo.py", line 247, in run
    self.runhistory.add(
  File "/home/user/anaconda3/envs/myenv/lib/python3.8/site-packages/smac/runhistory/runhistory.py", line 240, in add
    raise TypeError('Configuration to add to the runhistory must not be None')
TypeError: Configuration to add to the runhistory must not be None
```

#### Versions
smac 0.13.1

#### Thoughts
Is this related to this line?
https://github.com/automl/SMAC3/blob/60584751985b200c69e2bbb32d61f00f7d1d55d4/examples/SMAC4HPO_svm.py#L98
Changing it to`"deterministic": "true"` makes it run (Edit: I meant changing it to `"deterministic": "false"`), but then it changes the behaviour. I get worse results, because some configurations are run many times and I can't properly set `maxR`at the moment, see issue #676 .

**Comment by Mustrumion** [comment]
I am having the same issue with a custom algorithm. I am glad that this is reproducible with one of the examples.

By the way you intended to write:

> Changing it to `"deterministic": "false" ` ...

didn't you?

**Comment by mh415-f** [comment]
Yes, thanks for pointing it out. I edited it.

**Comment by Mustrumion** [comment]
I made a post in the #676 that describes how to get `maxR` to stick using Python facades, which makes the above behavior less painful.
It does not solve the problem directly, but hopefully will save someone time.
