### ISSUE TITLE
DASK Exception

### ISSUE THREAD

**Issue by FelixNeutatz** [automl/SMAC3#769]
Dear all,

I am currently running SMAC3 on a bigger machine with 28 CPUs and therefore, I wanted to use DASK to parallelize:
```
smac = SMAC4HPO(scenario=scenario,
                    rng=np.random.RandomState(42),
                    tae_runner=run_AutoML,
                    runhistory2epm=RunHistory2EPM4Cost,
                    acquisition_function=MyAquisitionFunction,
                    initial_design=LHDesign,
                    initial_design_kwargs={'n_configs_x_params': 2},
                    model=CustomRandomForest,
                    intensifier=SimpleIntensifier,
                    model_kwargs={'num_trees': 1000,
                                      'do_bootstrapping': True,
                                      'ratio_features': 1.0,
                                      'min_samples_split': 2,
                                      'min_samples_leaf': 1
                                      },
                    n_jobs=28
                    )
```
When I run it on my laptop it runs perfectly, but when I run it on the big machine, DASK throws exceptions:
```
OSError: Timed out during handshake while connecting to tcp://127.0.0.1:32920 after 10 s
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7f02e8b64390>>, <Task finished coro=<Worker.
heartbeat() done, defined at /home/neutatz/anaconda3/envs/AutoMLD/lib/python3.7/site-packages/distributed/worker.py:964> exception=OSError('Timed out during handshake while connecting to tcp://127.0.0.1:32920 af
ter 10 s')>)
Traceback (most recent call last):
  File "/home/neutatz/anaconda3/envs/AutoMLD/lib/python3.7/site-packages/distributed/comm/core.py", line 320, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/home/neutatz/anaconda3/envs/AutoMLD/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/neutatz/anaconda3/envs/AutoMLD/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/home/neutatz/anaconda3/envs/AutoMLD/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/home/neutatz/anaconda3/envs/AutoMLD/lib/python3.7/site-packages/distributed/worker.py", line 1015, in heartbeat
    raise e
  File "/home/neutatz/anaconda3/envs/AutoMLD/lib/python3.7/site-packages/distributed/worker.py", line 982, in heartbeat
    for key in active_keys
  File "/home/neutatz/anaconda3/envs/AutoMLD/lib/python3.7/site-packages/distributed/utils_comm.py", line 390, in retry_operation
    operation=operation,
  File "/home/neutatz/anaconda3/envs/AutoMLD/lib/python3.7/site-packages/distributed/utils_comm.py", line 370, in retry
    return await coro()
  File "/home/neutatz/anaconda3/envs/AutoMLD/lib/python3.7/site-packages/distributed/core.py", line 861, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/home/neutatz/anaconda3/envs/AutoMLD/lib/python3.7/site-packages/distributed/core.py", line 1016, in connect
    **self.connection_args,
  File "/home/neutatz/anaconda3/envs/AutoMLD/lib/python3.7/site-packages/distributed/comm/core.py", line 327, in connect
    ) from exc
```
Is this a known issue or is there a known workaround?

#### Versions
>>> import smac; print(smac.__version__)
0.13.1
>>> 

Thank you for your help.

Best regards,
Felix

**Comment by dengdifan** [comment]
Hi,

First you could reduce the number of trees in your `CustomRandomForest` to check if it is a memory issue (or n_jobs).
Then You could create a simple script running dask with your configuration on your cluster (something like this: https://github.com/automl/SMAC3/blob/master/smac/tae/dask_runner.py#L111,
https://github.com/automl/SMAC3/blob/master/smac/tae/dask_runner.py#L163) 

if the error still exists, then it should be a dask related-issue you could find some related information here:
https://github.com/dask/distributed/issues/2880

**Comment by FelixNeutatz** [comment]
Dear @dengdifan ,
thank you for your quick answer. You were right, it was a matter of large scale:
```
scenario = Scenario({"run_obj": "quality",  # we optimize quality (alternatively runtime)
                         "runcount-limit": 100000, 
                         "cs": cs,  # configuration space
                         "deterministic": "true"
                         })
```
The number of runs was too large. When I reduced the number of runs, the exception went away.

Thank you again.

Best regards,
Felix
