### ISSUE TITLE
`RandomFacade` + Callback result in crazy overhead

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#886]
When adding a callback to the random facade, SMAC generates crazy amounts of overhead.

Example:
```
import numpy as np
from ConfigSpace import Float, ConfigurationSpace

from smac import Callback, RandomFacade, Scenario


class cb(Callback):

    def on_iteration_start(self, smbo):
        pass

    def on_iteration_end(self, smbo):
        pass

smac = RandomFacade(
    scenario=Scenario(configspace=ConfigurationSpace(space={"a": (0, 1)})),
    target_function=lambda x, seed: x["a"] * seed,
    callbacks=[cb(), ]
)
smac.optimize()
```
The issue lies in `smbo.py`, where we [`copy.deepcopy` the `challengers`](https://github.com/automl/SMAC3/blob/a659b13d60562ec9ddd85a70882709b2ac00b787/smac/main/smbo.py#L85). However, this is a generator, which then generates (potentially endless amounts of) new configurations.

The resulting traceback when doing `CTRL^C` is
```
/home/feurerm/miniconda/3-4.12.0/envs/smac3/bin/python /home/feurerm/sync_dir/projects/smac3/local/bug.py 
[INFO][abstract_initial_design.py:133] Using 1 initial design and 0 additional configurations.
[INFO][intensifier.py:275] No incumbent provided in the first run. Sampling a new challenger...
[INFO][intensifier.py:446] First run and no incumbent provided. Challenger is assumed to be the incumbent.
[INFO][intensifier.py:566] Updated estimated cost of incumbent on 1 trials: 0.0
[INFO][intensifier.py:566] Updated estimated cost of incumbent on 2 trials: 0.0
Traceback (most recent call last):
  File "/home/feurerm/sync_dir/projects/smac3/local/bug.py", line 20, in <module>
    smac.optimize()
  File "/home/feurerm/sync_dir/projects/smac3/smac/facade/abstract_facade.py", line 318, in optimize
    incumbent = self._optimizer.optimize()
  File "/home/feurerm/sync_dir/projects/smac3/smac/main/base_smbo.py", line 194, in optimize
    intent, trial_info = self.ask()
  File "/home/feurerm/sync_dir/projects/smac3/smac/main/smbo.py", line 97, in ask
    intent, trial_info = self._intensifier.get_next_trial(
  File "/home/feurerm/sync_dir/projects/smac3/smac/intensifier/intensifier.py", line 325, in get_next_trial
    challenger, self._new_challenger = self.get_next_challenger(
  File "/home/feurerm/sync_dir/projects/smac3/smac/intensifier/intensifier.py", line 745, in get_next_challenger
    configs_to_run = self._generate_challengers(
  File "/home/feurerm/sync_dir/projects/smac3/smac/intensifier/intensifier.py", line 787, in _generate_challengers
    chall_gen = get_next_configurations()
  File "/home/feurerm/sync_dir/projects/smac3/smac/main/smbo.py", line 85, in get_next_configurations
    challenger_list = list(copy.deepcopy(challengers))
  File "/home/feurerm/sync_dir/projects/smac3/smac/acquisition/maximizer/helpers.py", line 55, in __next__
    config = self._configspace.sample_configuration()
KeyboardInterrupt

Process finished with exit code 130 (interrupted by signal 2: SIGINT)
```

**Comment by renesass** [comment]
I'm gonna remove the configs for this callback for now - or do you have a better solution?
