### ISSUE TITLE
Continue Run w/ Successive Halving fails

### ISSUE THREAD

**Issue by KEggensperger** [automl/SMAC3#907]
#### Description

Run SMAC using the multi-fidelity facade + Ask/Tell interface + Incumbent selection on the highest budget fails when I want to continue a run. This only happens when I set `incumbent_selection="highest_budget"`.

#### Steps/Code to Reproduce

This is a slightly modified version of the Rosenbrock example:

```
from ConfigSpace import Configuration, ConfigurationSpace, Float

from smac import MultiFidelityFacade, Scenario
from smac.runhistory.dataclasses import TrialValue

__copyright__ = "Copyright 2021, AutoML.org Freiburg-Hannover"
__license__ = "3-clause BSD"

class Rosenbrock2D:
    @property
    def configspace(self) -> ConfigurationSpace:
        cs = ConfigurationSpace(seed=0)
        x0 = Float("x0", (-5, 10), default=-3)
        x1 = Float("x1", (-5, 10), default=-4)
        cs.add_hyperparameters([x0, x1])

        return cs

    def train(self, config: Configuration, seed: int = 0, budget: int = 0) -> float:
        """The 2-dimensional Rosenbrock function as a toy model.
        The Rosenbrock function is well know in the optimization community and
        often serves as a toy problem. It can be defined for arbitrary
        dimensions. The minimium is always at x_i = 1 with a function value of
        zero. All input parameters are continuous. The search domain for
        all x's is the interval [-5, 10].
        """
        x1 = config["x0"]
        x2 = config["x1"]

        cost = 100.0 * (x2 - x1**2.0) ** 2.0 + (1 - x1) ** 2.0
        return cost


if __name__ == "__main__":
    model = Rosenbrock2D()

    # Scenario object
    scenario = Scenario(model.configspace, name="Rosenbrock",
                        deterministic=True, n_trials=1000,
                        min_budget=1,
                        max_budget=9,
                        )

    intensifier = MultiFidelityFacade.get_intensifier(
        scenario,
        incumbent_selection="highest_budget",
    )

    #initial_design = MultiFidelityFacade.get_initial_design(scenario, n_configs=5)

    # Now we use SMAC to find the best hyperparameters
    smac = MultiFidelityFacade(
        scenario,
        model.train,
        overwrite=False,
        intensifier=intensifier,
        #initial_design=initial_design,
    )

    # We can ask SMAC which trials should be evaluated next
    for _ in range(10):
        info = smac.ask()
        assert info.seed is not None
        print(info.config)
        cost = model.train(info.config, seed=info.seed)
        value = TrialValue(cost=cost, time=0.5)

        smac.tell(info, value)
```

#### Expected Results

When running this script multiple times, it should continue the SMAC run.

#### Actual Results

When running the script for the second time I receive the following:
```
[INFO][abstract_initial_design.py:133] Using 20 initial design configurations and 0 additional configurations.
[INFO][smbo.py:462] Continuing from previous run.
Traceback (most recent call last):
  File "/home/eggenspk/Work/Project/TEST/test_continue.py", line 63, in <module>
    info = smac.ask()
  File "/home/eggenspk/anaconda3/envs/soil_310/lib/python3.10/site-packages/smac/facade/abstract_facade.py", line 262, in ask
    return self._optimizer.ask()
  File "/home/eggenspk/anaconda3/envs/soil_310/lib/python3.10/site-packages/smac/main/smbo.py", line 151, in ask
    trial_info = next(self._trial_generator)
  File "/home/eggenspk/anaconda3/envs/soil_310/lib/python3.10/site-packages/smac/intensifier/successive_halving.py", line 300, in __iter__
    self.__post_init__()
  File "/home/eggenspk/anaconda3/envs/soil_310/lib/python3.10/site-packages/smac/intensifier/hyperband.py", line 21, in __post_init__
    super().__post_init__()
  File "/home/eggenspk/anaconda3/envs/soil_310/lib/python3.10/site-packages/smac/intensifier/successive_halving.py", line 116, in __post_init__
    super().__post_init__()
  File "/home/eggenspk/anaconda3/envs/soil_310/lib/python3.10/site-packages/smac/intensifier/abstract_intensifier.py", line 184, in __post_init__
    self.update_incumbents(config)
  File "/home/eggenspk/anaconda3/envs/soil_310/lib/python3.10/site-packages/smac/intensifier/abstract_intensifier.py", line 465, in update_incumbents
    config_isb_keys = self.get_instance_seed_budget_keys(config)
  File "/home/eggenspk/anaconda3/envs/soil_310/lib/python3.10/site-packages/smac/intensifier/successive_halving.py", line 289, in get_instance_seed_budget_keys
    isb_keys = [key for key in isb_keys if key.budget == self._max_budget]
  File "/home/eggenspk/anaconda3/envs/soil_310/lib/python3.10/site-packages/smac/intensifier/successive_halving.py", line 289, in <listcomp>
    isb_keys = [key for key in isb_keys if key.budget == self._max_budget]
AttributeError: 'Hyperband' object has no attribute '_max_budget'. Did you mean: '_tf_budgets'?
```

#### Versions

```
>>> import smac; print(smac.version)  #note: the issue template code "print(smac.__version__)" fails
2.0.0b1
```

**Comment by renesass** [comment]
Hey,

good spot! The problem happens because ``get_instance_seed_keys_of_interest`` requires ``max_budget`` which is defined in the post init method. We could set ``self._max_budget`` before we call ``get_instance_seed_keys_of_interest``. However, we don't know if max budget is valid and have to do the checks afterwards.

**Comment by alexandertornede** [comment]
Fixed due to René's commit.
